version: "3"

services:
    app:
        build:
           context: .
           dockerfile: Dockerfile
        image: go_auth_service
        environment:
            APP_ENV: development    # Can be: development, production, testing
            APP_HOST: goauth.dev    # For using with letsencrypt, only for production environment
            APP_PORT: ":80"          # Uses only in local environment
            APP_CACHE_DIR: "/var/www/.cache"
            DB_CONN: "user:password@tcp(db)/dbname?charset=utf8&parseTime=True&loc=Local"
            GIN_MODE: debug         # debug, release, test
        ports:
            - "8080:80"
        links:
            - db
        networks:
            - auth-back-end
            - auth-front-end

    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbname
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - auth-back-end
        # volumes:
        #     - ./docker/db:/docker-entrypoint-initdb.d

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            MAX_UPLOAD: "512M"
        networks:
            - auth-back-end
            - auth-front-end
        ports:
            - "8081:80"


networks:
    auth-back-end:
    auth-front-end:
